
truncate table cs110;
truncate table csgl_bmlinkinfo;
truncate table csgl_dxpfxxb;
delete csgl_dxkhxxb;
truncate table csgl_dxwh;
truncate table csgl_lbjxfxx;
truncate table csgl_sbmz;
truncate table csgl_zxjbxx;
truncate table csgl_zxjbxx;
truncate table dtj_ryinfo;
truncate table fxpg_zrzt;
truncate table gabm_hjxxxg;
truncate table gabm_xlldrk;
truncate table ggyj_center;
truncate table gsbm_xlldrk;
truncate table gsbm_ygryrk;
truncate table hmgc_jgbmxx;
truncate table jtbm_xlldrk;
truncate table mzbm_lhtb;
truncate table mzbm_mzbmtb;
truncate table mzbm_ylsy;
truncate table rlzy_xlldrk;
truncate table sys_jlrzdy;
truncate table wsbm_ldrkhy;
truncate table wsbm_ldrktb;
truncate table wsbm_xsetb;
truncate table wsbm_xsjyxxtb;
truncate table wsbm_zyxxtb;
truncate table xwxx_xzzbxx;
truncate table zfcj_czfldrkhyzm;
truncate table zfcj_fwzl;
truncate table zfcj_gdld;
truncate table zfcj_jzgd;
truncate table zfcj_ldrkgf;
truncate table zzww_bmlinkinfo;
truncate table zzww_dxpfxxb;
delete zzww_dxkhxxb;
truncate table zzww_dxwh;
truncate table zzww_lbjxfxx;
truncate table zzww_sbmz;
truncate table zzww_zxjbzfxx;
delete sys_deptinfo;
